spring:
  application:
    name: vehicle-sale-service

  datasource:
    url: jdbc:postgresql://localhost:5434/vehicle_sale_service_db
    username: vehicle_user
    password: vehicle_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
