spring.application.name=vehicle-sale-service
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5434/vehicle_sale_service_db}
spring.datasource.username=${JDBC_DATABASE_USERNAME:vehicle_user}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:vehicle_pass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

