apiVersion: v1
kind: Service
metadata:
  name: vehicle-sale-postgres
  namespace: vehicle-system
spec:
  type: ClusterIP
  selector:
    app: vehicle-sale-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432